# Generated by Django 5.0.3 on 2024-04-15 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardcraft', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='answer',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='card',
            name='question',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='cardsets',
            name='description',
            field=models.CharField(max_length=250),
        ),
    ]
